 version: '3.8'

 services:
  app:
    build:
      context: .
    container_name: weather-rest-service
    depends_on:
      - db
    ports:
      - "8085:8085"
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weatherrestservice
    ports:
      - 5434:5432